Liberty
f5devcentral/f5-openstack-ansible pull request #1
Opened 2017-01-03 18:20 UTC by pjbreaux

#### What's this change do?
This PR is to merge liberty into master. Once that is done, I will create a branch for liberty and mitaka based on the tip of master. Both liberty and mitaka installations of these playbooks have been tested.

#### Any background context?

#### Where should the reviewer start?
Review the license, contributing doc, and README file, just to make sure it's fit for public consumption.

2017-01-03 20:44 UTC, pjbreaux commented
All yaml files have been reviewed by @dflanigan, but feel free to peruse them if you'd like

2017-01-04 00:39 UTC, mattgreene requested changes

2017-01-04 00:39 UTC, mattgreene commented on CONTRIBUTING.md
> +Copyright 2016 F5 Networks Inc.
Fix copyright to include 2017.

2017-01-04 00:39 UTC, mattgreene commented on CONTRIBUTING.md
> +*  Use our pull request template
Create the magic .github directory with the following files:
PULL_REQUEST_TEMPLATE.md
ISSUE_TEMPLATE.md

See the agent repo for samples.

2017-01-04 00:39 UTC, mattgreene commented on README.rst
> +|slack badge|
I see the new ansible channel on F5OpenStack slack.  Are you also going to create a channel on F5OpenStackDev slack?

2017-01-04 00:39 UTC, mattgreene commented on playbooks/hosts
> +10.190.4.147 ansible_ssh_private_key_file=/root/.ssh/id_rsa_testlab ansible_ssh_extra_args='-o StrictHostKeyChecking=no'
Remove the real IP address so someone doesn't accidentally clober this machine in the future.

2017-01-04 00:39 UTC, mattgreene commented on playbooks/roles/configure_lbaasv2_agent/tasks/main.yml
> +---
Can you add a comment to this file simply to state that the agent ini contains many settings, but this file is starting with the most commonly used settings?  (and feel free to add more as required)

2017-01-04 00:39 UTC, mattgreene commented on playbooks/roles/configure_lbaasv2_agent/vars/main.yml
> +undercloud: true
We've been conflating over and under cloud with GRM or L2 Adjacent Mode.  Rename this with "f5_global_routed_mode" which can be use directly to populate the ini file.

2017-01-04 00:39 UTC, mattgreene commented on playbooks/vars/agent_configuration_vars.yaml
> +undercloud: <true_or_false>     # Set to true by default. Set to false if using an undercloud deployment.
See my previous comment in playbooks/roles/configure_lbaasv2_agent/vars/main.yml.  In fact, is the main.yml file necessary if this setting exists here?

2017-01-04 00:39 UTC, mattgreene commented on playbooks/vars/agent_configuration_vars.yaml
> +tunnel_types: <tunnel_type>     # vxlan, gre etc...
Rename to "advertised_tunnel_types" to match the same name in the ini file.

2017-01-04 00:39 UTC, mattgreene commented on playbooks/agent_driver_deploy.yaml
> +  roles:
We need to be able to locate the agent on a different host than the driver (neutron server).  Can we either split driver and agent apart into separate files, or somehow provide the 'roles' on a per host basis?

2017-01-04 17:06 UTC, pjbreaux commented on README.rst
> +|slack badge|
Done

2017-01-04 17:07 UTC, pjbreaux commented on playbooks/vars/agent_configuration_vars.yaml
> +undercloud: <true_or_false>     # Set to true by default. Set to false if using an undercloud deployment.
We can remove the file and require the user to set the value

2017-01-04 17:07 UTC, pjbreaux commented on playbooks/agent_driver_deploy.yaml
> +  roles:
This just sounds like a different playbook. Would you like me to add a new one?

2017-01-04 22:14 UTC, mattgreene commented on playbooks/agent_driver_deploy.yaml
> +  roles:
I prefer separate playbooks for driver and agent.

2017-01-04 22:14 UTC, mattgreene commented on playbooks/vars/agent_configuration_vars.yaml
> +undercloud: <true_or_false>     # Set to true by default. Set to false if using an undercloud deployment.
ok

2017-01-04 22:58 UTC, pjbreaux commented on playbooks/agent_driver_deploy.yaml
> +  roles:
Updating to add new playbooks for driver deployment, then a separate one for the agent deployment.

2017-01-05 23:39 UTC, pjbreaux commented
@mattgreene: I addressed your comments. I created two new playbooks. The deployment of the agent alone and of the driver alone. I kept the original playbook to deploy both as well. For each playbook, I add a vars file. One vars file would be more confusing to just deploy the agent, but we could do that, if you'd like.

2017-01-06 04:41 UTC, mattgreene commented
This code is fine for 'master', but when it splits into liberty and mitaka branches the vars file needs to reflect the correct package versions.  playbooks/vars/agent_deploy_vars.yaml refers to 9.1.0 (which is mitaka, though your PR origin branch is liberty).

2017-01-06 06:34 UTC, pjbreaux commented
Closing

2017-01-06 06:35 UTC, merged